### ISSUE TITLE
Support for multiple database environment in Exadata Cloud @ Customer

### ISSUE THREAD

**Issue by kranskydog** [oracle-samples/maa#1]
We are about to undertake migration from our Gen1 ExaCC to Gen2 ExaCC. The Data Guard Setup scripts will be very useful but the requirement that the DB environment variables are set in the the oracle user's bashrc is not feasible, as we have a large number of databases to migrate.
ExaCC creates a $HOME/$ORACLE_UNQNAME.env  file for every database, so it should be a simple thing to add in a call to this file in the 2 and 3 scripts immediately after the sourcing $HOME/.bashrc, based on A_DBNM and B_DBNM respectively.

**Comment by IratxeEtxebarria-MAA** [comment]
Implemented. Added optional custom env files in DG_properties.ini to support multi DB hosts
