### ISSUE TITLE
dg_broker_config_file parameters should have DBNM in the path 

### ISSUE THREAD

**Issue by kranskydog** [oracle-samples/maa#2]
in 3_dataguardit_standby_root.sh there is 

alter system set dg_broker_config_file1='${A_FILE_DEST}/dr1.dat';
alter system set dg_broker_config_file2='${A_RECOVERY_FILE_DEST}/dr2.dat';

if A_FILE_DEST='+DATA', this will not work if there is more than one database

should be
alter system set dg_broker_config_file1='${A_FILE_DEST}/${A_DBNM}/dr1.dat';
alter system set dg_broker_config_file2='${A_RECOVERY_FILE_DEST}/${A_DBNM}/dr2.dat';

Similarly for B_ for the standby

**Comment by IratxeEtxebarria-MAA** [comment]
Yes, thanks for catching this. File 3_dataguardit_standby_root.sh has been updated accordingly
